//=============================================================================
// This source code is a part of TatukGIS Developer Kernel.
// DKv100.1.37476
// (c)2000-2025 TatukGIS. ALL RIGHTS RESERVED.
//=============================================================================

const GIS_VERSION   = 'v100.1.37476';
const GIS_COPYRIGHT = '(c)2000-2025 TatukGIS. All Rights Reserved.';
const GIS_PRODUCTID = 'DK.Delphi.Source';


