ren FMX.GisCanvasFix.pas  Lider.CG.GIS.FMX.GeoCanvasFix.pas
ren FMX.GisComboBox.pas  Lider.CG.GIS.FMX.GeoComboBox.pas
ren FMX.GisComboBoxHelper.pas  Lider.CG.GIS.FMX.GeoComboBoxHelper.pas
ren FMX.GisControl3D.pas  Lider.CG.GIS.FMX.GeoControl3D.pas
ren FMX.GisControlAttributes.pas  Lider.CG.GIS.FMX.GeoControlAttributes.pas
ren FMX.GisControlAttributesForm.pas  Lider.CG.GIS.FMX.GeoControlAttributesForm.pas
ren FMX.GisControlColor.pas  Lider.CG.GIS.FMX.GeoControlColor.pas
ren FMX.GisControlCsHelper.pas  Lider.CG.GIS.FMX.GeoControlCsHelper.pas
ren FMX.GisControlCsSystem.pas  Lider.CG.GIS.FMX.GeoControlCsSystem.pas
ren FMX.GisControlCsSystemSetup.pas  Lider.CG.GIS.FMX.GeoControlCsSystemSetup.pas
ren FMX.GisControlFieldFactor.pas  Lider.CG.GIS.FMX.GeoControlFieldFactor.pas
ren FMX.GisControlHelper.pas  Lider.CG.GIS.FMX.GeoControlHelper.pas
ren FMX.GisControlLegend.pas  Lider.CG.GIS.FMX.GeoControlLegend.pas
ren FMX.GisControlLegendBMP.pas  Lider.CG.GIS.FMX.GeoControlLegendBMP.pas
ren FMX.GisControlLegendFNT.pas  Lider.CG.GIS.FMX.GeoControlLegendFNT.pas
ren FMX.GisControlLegendForm.pas  Lider.CG.GIS.FMX.GeoControlLegendForm.pas
ren FMX.GisControlLegendGridWiz.pas  Lider.CG.GIS.FMX.GeoControlLegendGridWiz.pas
ren FMX.GisControlLegendLIB.pas  Lider.CG.GIS.FMX.GeoControlLegendLIB.pas
ren FMX.GisControlLegendSYM.pas  Lider.CG.GIS.FMX.GeoControlLegendSYM.pas
ren FMX.GisControlLegendVectorWiz.pas  Lider.CG.GIS.FMX.GeoControlLegendVectorWiz.pas
ren FMX.GisControlNorthArrow.pas  Lider.CG.GIS.FMX.GeoControlNorthArrow.pas
ren FMX.GisControlPrintPreview.pas  Lider.CG.GIS.FMX.GeoControlPrintPreview.pas
ren FMX.GisControlScale.pas  Lider.CG.GIS.FMX.GeoControlScale.pas
ren FMX.GisControlSizeForm.pas  Lider.CG.GIS.FMX.GeoControlSizeForm.pas
ren FMX.GisControlVarious.pas  Lider.CG.GIS.FMX.GeoControlVarious.pas
ren FMX.GisFramework.pas  Lider.CG.GIS.FMX.GeoFramework.pas
ren FMX.GisLegendUtilsFactory.pas  Lider.CG.GIS.FMX.GeoLegendUtilsFactory.pas
ren FMX.GisLineSymbolEditor.pas  Lider.CG.GIS.FMX.GeoLineSymbolEditor.pas
ren FMX.GisModalForm.pas  Lider.CG.GIS.FMX.GeoModalForm.pas
ren FMX.GisPrinters.pas  Lider.CG.GIS.FMX.GeoPrinters.pas
ren FMX.GisPrintLegend.pas  Lider.CG.GIS.FMX.GeoPrintLegend.pas
ren FMX.GisPrintManager.pas  Lider.CG.GIS.FMX.GeoPrintManager.pas
ren FMX.GisRenderer.pas  Lider.CG.GIS.FMX.GeoRenderer.pas
ren FMX.GisRenderer3D.pas  Lider.CG.GIS.FMX.GeoRenderer3D.pas
ren FMX.GisValueValidatorHelper.pas  Lider.CG.GIS.FMX.GeoValueValidatorHelper.pas
ren FMX.GisViewer3D.pas  Lider.CG.GIS.FMX.GeoViewer3D.pas
ren FMX.GisViewerBmp.pas  Lider.CG.GIS.FMX.GeoViewerBmp.pas
ren FMX.GisViewerWnd.pas  Lider.CG.GIS.FMX.GeoViewerWnd.pas
ren FMX.Mobile.GisControlCsSystem.pas  Lider.CG.GIS.FMX.Mobile.GeoControlCsSystem.pas
ren Gis3DFlyOver.pas  Lider.CG.GIS.Geo3DFlyOver.pas
ren GisAddressMatching.pas  Lider.CG.GIS.GeoAddressMatching.pas
ren GisAdoInt.pas  Lider.CG.GIS.GeoAdoInt.pas
ren GisAdoxInt.pas  Lider.CG.GIS.GeoAdoxInt.pas
ren GisAllBasicLayers.pas  Lider.CG.GIS.GeoAllBasicLayers.pas
ren GisAllEnterpriseLayers.pas  Lider.CG.GIS.GeoAllEnterpriseLayers.pas
ren GisAllLayers.pas  Lider.CG.GIS.GeoAllLayers.pas
ren GisArcLabel.pas  Lider.CG.GIS.GeoArcLabel.pas
ren GisBasemapHelper.pas  Lider.CG.GIS.GeoBasemapHelper.pas
ren GisChart.pas  Lider.CG.GIS.GeoChart.pas
ren GisClasses.pas  Lider.CG.GIS.GeoClasses.pas
ren GisCompression.pas  Lider.CG.GIS.GeoCompression.pas
ren GisConfig.pas  Lider.CG.GIS.GeoConfig.pas
ren GisConfigIni.pas  Lider.CG.GIS.GeoConfigIni.pas
ren GisConfigXml.pas  Lider.CG.GIS.GeoConfigXml.pas
ren GisContour.pas  Lider.CG.GIS.GeoContour.pas
ren GisControlLegendFormControler.pas  Lider.CG.GIS.GeoControlLegendFormControler.pas
ren GisControlPrintPreviewSimple.pas  Lider.CG.GIS.GeoControlPrintPreviewSimple.pas
ren GisCsBase.pas  Lider.CG.GIS.GeoCsBase.pas
ren GisCsEsri.pas  Lider.CG.GIS.GeoCsEsri.pas
ren GisCsFactory.pas  Lider.CG.GIS.GeoCsFactory.pas
ren GisCsMapinfo.pas  Lider.CG.GIS.GeoCsMapinfo.pas
ren GisCsProjections.pas  Lider.CG.GIS.GeoCsProjections.pas
ren GisCsSystems.pas  Lider.CG.GIS.GeoCsSystems.pas
ren GisDaoInt.pas  Lider.CG.GIS.GeoDaoInt.pas
ren GisDataSet.pas  Lider.CG.GIS.GeoDataSet.pas
ren GisDb.pas  Lider.CG.GIS.GeoDb.pas
ren GisDbAdo.pas  Lider.CG.GIS.GeoDbAdo.pas
ren GisDbAdoNet.pas  Lider.CG.GIS.GeoDbAdoNet.pas
ren GisDbDbx.pas  Lider.CG.GIS.GeoDbDbx.pas
ren GisDbFireDac.pas  Lider.CG.GIS.GeoDbFireDac.pas
ren GisDbSqlite.pas  Lider.CG.GIS.GeoDbSqlite.pas
ren GisDem.pas  Lider.CG.GIS.GeoDem.pas
ren GisDirectXLite.pas  Lider.CG.GIS.GeoDirectXLite.pas
ren GisEditor.pas  Lider.CG.GIS.GeoEditor.pas
ren GisFieldRules.pas  Lider.CG.GIS.GeoFieldRules.pas
ren GisFile8211.pas  Lider.CG.GIS.GeoFile8211.pas
ren GisFileBMP.pas  Lider.CG.GIS.GeoFileBMP.pas
ren GisFileCADRG.pas  Lider.CG.GIS.GeoFileCADRG.pas
ren GisFileDBF.pas  Lider.CG.GIS.GeoFileDBF.pas
ren GisFileDWG.pas  Lider.CG.GIS.GeoFileDWG.pas
ren GisFileFGDB.pas  Lider.CG.GIS.GeoFileFGDB.pas
ren GisFileFLT.pas  Lider.CG.GIS.GeoFileFLT.pas
ren GisFileGDAL.pas  Lider.CG.GIS.GeoFileGDAL.pas
ren GisFileGPB.pas  Lider.CG.GIS.GeoFileGPB.pas
ren GisFileGRD.pas  Lider.CG.GIS.GeoFileGRD.pas
ren GisFileJPEG.pas  Lider.CG.GIS.GeoFileJPEG.pas
ren GisFileJSON.pas  Lider.CG.GIS.GeoFileJSON.pas
ren GisFileLAS.pas  Lider.CG.GIS.GeoFileLAS.pas
ren GisFilePBF.pas  Lider.CG.GIS.GeoFilePBF.pas
ren GisFilePixel.pas  Lider.CG.GIS.GeoFilePixel.pas
ren GisFilePixelStore.pas  Lider.CG.GIS.GeoFilePixelStore.pas
ren GisFilePixelStoreAdo.pas  Lider.CG.GIS.GeoFilePixelStoreAdo.pas
ren GisFilePixelStoreAdoNet.pas  Lider.CG.GIS.GeoFilePixelStoreAdoNet.pas
ren GisFilePixelStoreDbx.pas  Lider.CG.GIS.GeoFilePixelStoreDbx.pas
ren GisFilePixelStoreFireDac.pas  Lider.CG.GIS.GeoFilePixelStoreFireDac.pas
ren GisFilePixelStoreSqlite.pas  Lider.CG.GIS.GeoFilePixelStoreSqlite.pas
ren GisFilePNG.pas  Lider.CG.GIS.GeoFilePNG.pas
ren GisFileS57.pas  Lider.CG.GIS.GeoFileS57.pas
ren GisFileSDTS.pas  Lider.CG.GIS.GeoFileSDTS.pas
ren GisFileSHP.pas  Lider.CG.GIS.GeoFileSHP.pas
ren GisFileSVG.pas  Lider.CG.GIS.GeoFileSVG.pas
ren GisFileTAB.pas  Lider.CG.GIS.GeoFileTAB.pas
ren GisFileTIFF.pas  Lider.CG.GIS.GeoFileTIFF.pas
ren GisFileVPF.pas  Lider.CG.GIS.GeoFileVPF.pas
ren GisFileWFS.pas  Lider.CG.GIS.GeoFileWFS.pas
ren GisFileWMS.pas  Lider.CG.GIS.GeoFileWMS.pas
ren GisFMEInt.pas  Lider.CG.GIS.GeoFMEInt.pas
ren GisFunctions.pas  Lider.CG.GIS.GeoFunctions.pas
ren GisGeocoding.pas  Lider.CG.GIS.GeoGeocoding.pas
ren GisGeometryFactory.pas  Lider.CG.GIS.GeoGeometryFactory.pas
ren GisGestureHelper.pas  Lider.CG.GIS.GeoGestureHelper.pas
ren GisHierarchy.pas  Lider.CG.GIS.GeoHierarchy.pas
ren GisHtmlLabel.pas  Lider.CG.GIS.GeoHtmlLabel.pas
ren GisImportProject.pas  Lider.CG.GIS.GeoImportProject.pas
ren GisInclude.inc  Lider.CG.GIS.GeoInclude.inc
ren GisIniFiles.pas  Lider.CG.GIS.GeoIniFiles.pas
ren GisInterfaces.pas  Lider.CG.GIS.GeoInterfaces.pas
ren GisInternals.pas  Lider.CG.GIS.GeoInternals.pas
ren GisInterpolation.pas  Lider.CG.GIS.GeoInterpolation.pas
ren GisIsochroneMap.pas  Lider.CG.GIS.GeoIsochroneMap.pas
ren GisLabelsArea.pas  Lider.CG.GIS.GeoLabelsArea.pas
ren GisLayer.pas  Lider.CG.GIS.GeoLayer.pas
ren GisLayerADF.pas  Lider.CG.GIS.GeoLayerADF.pas
ren GisLayerBIL.pas  Lider.CG.GIS.GeoLayerBIL.pas
ren GisLayerBMP.pas  Lider.CG.GIS.GeoLayerBMP.pas
ren GisLayerBT.pas  Lider.CG.GIS.GeoLayerBT.pas
ren GisLayerCADRG.pas  Lider.CG.GIS.GeoLayerCADRG.pas
ren GisLayerCompound.pas  Lider.CG.GIS.GeoLayerCompound.pas
ren GisLayerCSV.pas  Lider.CG.GIS.GeoLayerCSV.pas
ren GisLayerDEM.pas  Lider.CG.GIS.GeoLayerDEM.pas
ren GisLayerDGN.pas  Lider.CG.GIS.GeoLayerDGN.pas
ren GisLayerDLG.pas  Lider.CG.GIS.GeoLayerDLG.pas
ren GisLayerDTED.pas  Lider.CG.GIS.GeoLayerDTED.pas
ren GisLayerDWG.pas  Lider.CG.GIS.GeoLayerDWG.pas
ren GisLayerDXF.pas  Lider.CG.GIS.GeoLayerDXF.pas
ren GisLayerE00.pas  Lider.CG.GIS.GeoLayerE00.pas
ren GisLayerECW.pas  Lider.CG.GIS.GeoLayerECW.pas
ren GisLayerFGDB.pas  Lider.CG.GIS.GeoLayerFGDB.pas
ren GisLayerFLT.pas  Lider.CG.GIS.GeoLayerFLT.pas
ren GisLayerFME.pas  Lider.CG.GIS.GeoLayerFME.pas
ren GisLayerGDAL.pas  Lider.CG.GIS.GeoLayerGDAL.pas
ren GisLayerGDF.pas  Lider.CG.GIS.GeoLayerGDF.pas
ren GisLayerGIF.pas  Lider.CG.GIS.GeoLayerGIF.pas
ren GisLayerGML.pas  Lider.CG.GIS.GeoLayerGML.pas
ren GisLayerGPX.pas  Lider.CG.GIS.GeoLayerGPX.pas
ren GisLayerGRD.pas  Lider.CG.GIS.GeoLayerGRD.pas
ren GisLayerGSHHS.pas  Lider.CG.GIS.GeoLayerGSHHS.pas
ren GisLayerIMG.pas  Lider.CG.GIS.GeoLayerIMG.pas
ren GisLayerJPG.pas  Lider.CG.GIS.GeoLayerJPG.pas
ren GisLayerJSON.pas  Lider.CG.GIS.GeoLayerJSON.pas
ren GisLayerKML.pas  Lider.CG.GIS.GeoLayerKML.pas
ren GisLayerLandXML.pas  Lider.CG.GIS.GeoLayerLandXML.pas
ren GisLayerLAS.pas  Lider.CG.GIS.GeoLayerLAS.pas
ren GisLayerMIF.pas  Lider.CG.GIS.GeoLayerMIF.pas
ren GisLayerMrSID.pas  Lider.CG.GIS.GeoLayerMrSID.pas
ren GisLayerOGR.pas  Lider.CG.GIS.GeoLayerOGR.pas
ren GisLayerOSM.pas  Lider.CG.GIS.GeoLayerOSM.pas
ren GisLayerPixel.pas  Lider.CG.GIS.GeoLayerPixel.pas
ren GisLayerPixelSql.pas  Lider.CG.GIS.GeoLayerPixelSql.pas
ren GisLayerPixelStore.pas  Lider.CG.GIS.GeoLayerPixelStore.pas
ren GisLayerPixelStoreAdo.pas  Lider.CG.GIS.GeoLayerPixelStoreAdo.pas
ren GisLayerPixelStoreAdoNet.pas  Lider.CG.GIS.GeoLayerPixelStoreAdoNet.pas
ren GisLayerPixelStoreDbx.pas  Lider.CG.GIS.GeoLayerPixelStoreDbx.pas
ren GisLayerPixelStoreFireDac.pas  Lider.CG.GIS.GeoLayerPixelStoreFireDac.pas
ren GisLayerPixelStoreSqlite.pas  Lider.CG.GIS.GeoLayerPixelStoreSqlite.pas
ren GisLayerPixelUDF.pas  Lider.CG.GIS.GeoLayerPixelUDF.pas
ren GisLayerPLY.pas  Lider.CG.GIS.GeoLayerPLY.pas
ren GisLayerPNG.pas  Lider.CG.GIS.GeoLayerPNG.pas
ren GisLayerProject.pas  Lider.CG.GIS.GeoLayerProject.pas
ren GisLayerS57.pas  Lider.CG.GIS.GeoLayerS57.pas
ren GisLayerSDTS.pas  Lider.CG.GIS.GeoLayerSDTS.pas
ren GisLayerSHP.pas  Lider.CG.GIS.GeoLayerSHP.pas
ren GisLayerSql.pas  Lider.CG.GIS.GeoLayerSql.pas
ren GisLayerSqlAdo.pas  Lider.CG.GIS.GeoLayerSqlAdo.pas
ren GisLayerSqlAdoNet.pas  Lider.CG.GIS.GeoLayerSqlAdoNet.pas
ren GisLayerSqlDbx.pas  Lider.CG.GIS.GeoLayerSqlDbx.pas
ren GisLayerSqlFireDac.pas  Lider.CG.GIS.GeoLayerSqlFireDac.pas
ren GisLayerSqlGm.pas  Lider.CG.GIS.GeoLayerSqlGm.pas
ren GisLayerSqlGmAdo.pas  Lider.CG.GIS.GeoLayerSqlGmAdo.pas
ren GisLayerSqlGmDbx.pas  Lider.CG.GIS.GeoLayerSqlGmDbx.pas
ren GisLayerSqlGmFireDac.pas  Lider.CG.GIS.GeoLayerSqlGmFireDac.pas
ren GisLayerSqlGpkg.pas  Lider.CG.GIS.GeoLayerSqlGpkg.pas
ren GisLayerSqlGpkgSqlite.pas  Lider.CG.GIS.GeoLayerSqlGpkgSqlite.pas
ren GisLayerSqlOgis.pas  Lider.CG.GIS.GeoLayerSqlOgis.pas
ren GisLayerSqlOgisAdo.pas  Lider.CG.GIS.GeoLayerSqlOgisAdo.pas
ren GisLayerSqlOgisAdoNet.pas  Lider.CG.GIS.GeoLayerSqlOgisAdoNet.pas
ren GisLayerSqlOgisDbx.pas  Lider.CG.GIS.GeoLayerSqlOgisDbx.pas
ren GisLayerSqlOgisFireDac.pas  Lider.CG.GIS.GeoLayerSqlOgisFireDac.pas
ren GisLayerSqlOgisSqlite.pas  Lider.CG.GIS.GeoLayerSqlOgisSqlite.pas
ren GisLayerSqlPgdb.pas  Lider.CG.GIS.GeoLayerSqlPgdb.pas
ren GisLayerSqlPgdbAdo.pas  Lider.CG.GIS.GeoLayerSqlPgdbAdo.pas
ren GisLayerSqlPgdbDbx.pas  Lider.CG.GIS.GeoLayerSqlPgdbDbx.pas
ren GisLayerSqlPgdbFireDac.pas  Lider.CG.GIS.GeoLayerSqlPgdbFireDac.pas
ren GisLayerSqlSqlite.pas  Lider.CG.GIS.GeoLayerSqlSqlite.pas
ren GisLayerSRTM.pas  Lider.CG.GIS.GeoLayerSRTM.pas
ren GisLayerSTL.pas  Lider.CG.GIS.GeoLayerSTL.pas
ren GisLayerSublayer.pas  Lider.CG.GIS.GeoLayerSublayer.pas
ren GisLayerTAB.pas  Lider.CG.GIS.GeoLayerTAB.pas
ren GisLayerTIFF.pas  Lider.CG.GIS.GeoLayerTIFF.pas
ren GisLayerTiger.pas  Lider.CG.GIS.GeoLayerTiger.pas
ren GisLayerVector.pas  Lider.CG.GIS.GeoLayerVector.pas
ren GisLayerVectorSql.pas  Lider.CG.GIS.GeoLayerVectorSql.pas
ren GisLayerVectorUDF.pas  Lider.CG.GIS.GeoLayerVectorUDF.pas
ren GisLayerVPF.pas  Lider.CG.GIS.GeoLayerVPF.pas
ren GisLayerWebTiles.pas  Lider.CG.GIS.GeoLayerWebTiles.pas
ren GisLayerWFS.pas  Lider.CG.GIS.GeoLayerWFS.pas
ren GisLayerWMS.pas  Lider.CG.GIS.GeoLayerWMS.pas
ren GisLayerWMTS.pas  Lider.CG.GIS.GeoLayerWMTS.pas
ren GisLayerXYZ.pas  Lider.CG.GIS.GeoLayerXYZ.pas
ren GisLegendUtils.pas  Lider.CG.GIS.GeoLegendUtils.pas
ren GisLibrarySVG.pas  Lider.CG.GIS.GeoLibrarySVG.pas
ren GisLineSymbolEditorUtils.pas  Lider.CG.GIS.GeoLineSymbolEditorUtils.pas
ren GisLogger.pas  Lider.CG.GIS.GeoLogger.pas
ren GisMatrix.pas  Lider.CG.GIS.GeoMatrix.pas
ren GisNetwork.pas  Lider.CG.GIS.GeoNetwork.pas
ren GisParams.pas  Lider.CG.GIS.GeoParams.pas
ren GisPixelExportManager.pas  Lider.CG.GIS.GeoPixelExportManager.pas
ren GisPrintManagerAbstract.pas  Lider.CG.GIS.GeoPrintManagerAbstract.pas
ren GisPrintPreviewHelperAbstract.pas  Lider.CG.GIS.GeoPrintPreviewHelperAbstract.pas
ren GisProjectQgis.pas  Lider.CG.GIS.GeoProjectQgis.pas
ren GisQuadTree.pas  Lider.CG.GIS.GeoQuadTree.pas
ren GisRegistredLayers.pas  Lider.CG.GIS.GeoRegistredLayers.pas
ren GisRenderer3DAbstract.pas  Lider.CG.GIS.GeoRenderer3DAbstract.pas
ren GisRenderer3DDirectX9.pas  Lider.CG.GIS.GeoRenderer3DDirectX9.pas
ren GisRenderer3DDirectXAbstract.pas  Lider.CG.GIS.GeoRenderer3DDirectXAbstract.pas
ren GisRendererAbstract.pas  Lider.CG.GIS.GeoRendererAbstract.pas
ren GisResource.inc  Lider.CG.GIS.GeoResource.inc
ren GisResource.pas  Lider.CG.GIS.GeoResource.pas
ren GisResourceEx.pas  Lider.CG.GIS.GeoResourceEx.pas
ren GisRestServices.pas  Lider.CG.GIS.GeoRestServices.pas
ren GisRtl.pas  Lider.CG.GIS.GeoRtl.pas
ren GisRTree.pas  Lider.CG.GIS.GeoRTree.pas
ren GisShapes3D.pas  Lider.CG.GIS.GeoShapes3D.pas
ren GisSharedConnections.pas  Lider.CG.GIS.GeoSharedConnections.pas
ren GisShortestPath.pas  Lider.CG.GIS.GeoShortestPath.pas
ren GisSldFiles.pas  Lider.CG.GIS.GeoSldFiles.pas
ren GisSlopeMap.pas  Lider.CG.GIS.GeoSlopeMap.pas
ren GisSqlQuery.pas  Lider.CG.GIS.GeoSqlQuery.pas
ren GisStreams.pas  Lider.CG.GIS.GeoStreams.pas
ren GisStringFormat.pas  Lider.CG.GIS.GeoStringFormat.pas
ren GisSymbol.pas  Lider.CG.GIS.GeoSymbol.pas
ren GisTemplatePrint.pas  Lider.CG.GIS.GeoTemplatePrint.pas
ren GisTopology.pas  Lider.CG.GIS.GeoTopology.pas
ren GisTransform.pas  Lider.CG.GIS.GeoTransform.pas
ren GisTriangulation.pas  Lider.CG.GIS.GeoTriangulation.pas
ren GisTypes.pas  Lider.CG.GIS.GeoTypes.pas
ren GisTypes3D.pas  Lider.CG.GIS.GeoTypes3D.pas
ren GisTypesUI.pas  Lider.CG.GIS.GeoTypesUI.pas
ren GisUtils.pas  Lider.CG.GIS.GeoUtils.pas
ren GisVersion.inc  Lider.CG.GIS.GeoVersion.inc
ren GisViewer.pas  Lider.CG.GIS.GeoViewer.pas
ren GisViewer3DBase.pas  Lider.CG.GIS.GeoViewer3DBase.pas
ren GisViewer3DDirectX.pas  Lider.CG.GIS.GeoViewer3DDirectX.pas
ren GisViewerWndHelper.pas  Lider.CG.GIS.GeoViewerWndHelper.pas
ren GisViewshed.pas  Lider.CG.GIS.GeoViewshed.pas
ren GisXmlDoc.pas  Lider.CG.GIS.GeoXmlDoc.pas
ren GisXmlFiles.pas  Lider.CG.GIS.GeoXmlFiles.pas
ren GisXmlSax.pas  Lider.CG.GIS.GeoXmlSax.pas
ren VCL.GisComboBoxHelper.pas  Lider.CG.GIS.VCL.GeoComboBoxHelper.pas
ren VCL.GisControl3D.pas  Lider.CG.GIS.VCL.GeoControl3D.pas
ren VCL.GisControlAttributes.pas  Lider.CG.GIS.VCL.GeoControlAttributes.pas
ren VCL.GisControlAttributesForm.pas  Lider.CG.GIS.VCL.GeoControlAttributesForm.pas
ren VCL.GisControlColor.pas  Lider.CG.GIS.VCL.GeoControlColor.pas
ren VCL.GisControlCsHelper.pas  Lider.CG.GIS.VCL.GeoControlCsHelper.pas
ren VCL.GisControlCsSystem.pas  Lider.CG.GIS.VCL.GeoControlCsSystem.pas
ren VCL.GisControlCsSystemSetup.pas  Lider.CG.GIS.VCL.GeoControlCsSystemSetup.pas
ren VCL.GisControlFieldFactor.pas  Lider.CG.GIS.VCL.GeoControlFieldFactor.pas
ren VCL.GisControlHelper.pas  Lider.CG.GIS.VCL.GeoControlHelper.pas
ren VCL.GisControlLegend.pas  Lider.CG.GIS.VCL.GeoControlLegend.pas
ren VCL.GisControlLegendBMP.pas  Lider.CG.GIS.VCL.GeoControlLegendBMP.pas
ren VCL.GisControlLegendFNT.pas  Lider.CG.GIS.VCL.GeoControlLegendFNT.pas
ren VCL.GisControlLegendForm.pas  Lider.CG.GIS.VCL.GeoControlLegendForm.pas
ren VCL.GisControlLegendGridWiz.pas  Lider.CG.GIS.VCL.GeoControlLegendGridWiz.pas
ren VCL.GisControlLegendLIB.pas  Lider.CG.GIS.VCL.GeoControlLegendLIB.pas
ren VCL.GisControlLegendSYM.pas  Lider.CG.GIS.VCL.GeoControlLegendSYM.pas
ren VCL.GisControlLegendVectorWiz.pas  Lider.CG.GIS.VCL.GeoControlLegendVectorWiz.pas
ren VCL.GisControlNorthArrow.pas  Lider.CG.GIS.VCL.GeoControlNorthArrow.pas
ren VCL.GisControlPrintPreview.pas  Lider.CG.GIS.VCL.GeoControlPrintPreview.pas
ren VCL.GisControlScale.pas  Lider.CG.GIS.VCL.GeoControlScale.pas
ren VCL.GisControlSizeForm.pas  Lider.CG.GIS.VCL.GeoControlSizeForm.pas
ren VCL.GisControlVarious.pas  Lider.CG.GIS.VCL.GeoControlVarious.pas
ren VCL.GisFramework.pas  Lider.CG.GIS.VCL.GeoFramework.pas
ren VCL.GisGdiPlus.pas  Lider.CG.GIS.VCL.GeoGdiPlus.pas
ren VCL.GisGps.pas  Lider.CG.GIS.VCL.GeoGps.pas
ren VCL.GisLegendUtilsFactory.pas  Lider.CG.GIS.VCL.GeoLegendUtilsFactory.pas
ren VCL.GisLineSymbolEditor.pas  Lider.CG.GIS.VCL.GeoLineSymbolEditor.pas
ren VCL.GisLineSymbolEditor.pass  Lider.CG.GIS.VCL.GeoLineSymbolEditor.pass
ren VCL.GisModalForm.pas  Lider.CG.GIS.VCL.GeoModalForm.pas
ren VCL.GisPrinters.pas  Lider.CG.GIS.VCL.GeoPrinters.pas
ren VCL.GisPrintLegend.pas  Lider.CG.GIS.VCL.GeoPrintLegend.pas
ren VCL.GisPrintManager.pas  Lider.CG.GIS.VCL.GeoPrintManager.pas
ren VCL.GisRenderer.pas  Lider.CG.GIS.VCL.GeoRenderer.pas
ren VCL.GisRendererDirect2D.pas  Lider.CG.GIS.VCL.GeoRendererDirect2D.pas
ren VCL.GisRendererGdi32.pas  Lider.CG.GIS.VCL.GeoRendererGdi32.pas
ren VCL.GisRendererGdiPlus.pas  Lider.CG.GIS.VCL.GeoRendererGdiPlus.pas
ren VCL.GisRendererGR32.pas  Lider.CG.GIS.VCL.GeoRendererGR32.pas
ren VCL.GisValueValidatorHelper.pas  Lider.CG.GIS.VCL.GeoValueValidatorHelper.pas
ren VCL.GisViewerBmp.pas  Lider.CG.GIS.VCL.GeoViewerBmp.pas
ren VCL.GisViewerWnd.pas  Lider.CG.GIS.VCL.GeoViewerWnd.pas
ren FMX.GisControlStatistics.pas  Lider.CG.GIS.FMX.GeoControlStatistics.pas
ren FMX.GisModalFormPvl.pas  Lider.CG.GIS.FMX.GeoModalFormPvl.pas
ren FMX.GisPvl.pas  Lider.CG.GIS.FMX.GeoPvl.pas
ren GisGraticuleHelper.pas  Lider.CG.GIS.GeoGraticuleHelper.pas
ren GisHydrology.pas  Lider.CG.GIS.GeoHydrology.pas
ren GisMVTStyler.pas  Lider.CG.GIS.GeoMVTStyler.pas
ren GisOSMServices.pas  Lider.CG.GIS.GeoOSMServices.pas
ren PVL.GisControlFieldFactor.pas  Lider.CG.GIS.PVL.GeoControlFieldFactor.pas
ren PVL.GisControlLegendBMP.pas  Lider.CG.GIS.PVL.GeoControlLegendBMP.pas
ren PVL.GisControlLegendFNT.pas  Lider.CG.GIS.PVL.GeoControlLegendFNT.pas
ren PVL.GisControlLegendLIB.pas  Lider.CG.GIS.PVL.GeoControlLegendLIB.pas
ren PVL.GisControlLegendSYM.pas  Lider.CG.GIS.PVL.GeoControlLegendSYM.pas
ren PVL.GisControlSizeForm.pas  Lider.CG.GIS.PVL.GeoControlSizeForm.pas
ren PVL.GisPvl.pas  Lider.CG.GIS.PVL.GeoPvl.pas
ren PVL.GisValueValidatorHelper.pas  Lider.CG.GIS.PVL.GeoValueValidatorHelper.pas
ren VCL.GisControlStatistics.pas  Lider.CG.GIS.VCL.GeoControlStatistics.pas
ren VCL.GisModalFormPvl.pas  Lider.CG.GIS.VCL.GeoModalFormPvl.pas
ren VCL.GisPvl.pas  Lider.CG.GIS.VCL.GeoPvl.pas
ren FMX.GisFormPvl.pas Lider.CG.GIS.FMX.GeoFormPvl.pas
ren FMX.GisModalWizardPvl.pas Lider.CG.GIS.FMX.GeoModalWizardPvl.pas
ren GisAggregator.pas Lider.CG.GIS.GeoAggregator.pas
ren GisAllPipelineOperations.pas Lider.CG.GIS.GeoAllPipelineOperations.pas
ren GisClassification.pas Lider.CG.GIS.GeoClassification.pas
ren GisCUDA.pas Lider.CG.GIS.GeoCUDA.pas
ren GisFileAssimp.pas Lider.CG.GIS.GeoFileAssimp.pas
ren GisFileWCS.pas Lider.CG.GIS.GeoFileWCS.pas
ren GisFourierTransform.pas Lider.CG.GIS.GeoFourierTransform.pas
ren GisHillshade.pas Lider.CG.GIS.GeoHillshade.pas
ren GisLayerAssimp.pas Lider.CG.GIS.GeoLayerAssimp.pas
ren GisLayerMVT.pas Lider.CG.GIS.GeoLayerMVT.pas
ren GisLayerSGRD.pas Lider.CG.GIS.GeoLayerSGRD.pas
ren GisLayerWCS.pas Lider.CG.GIS.GeoLayerWCS.pas
ren GisLegend.pas Lider.CG.GIS.GeoLegend.pas
ren GisOpenCL.pas Lider.CG.GIS.GeoOpenCL.pas
ren GisPipeline.pas Lider.CG.GIS.GeoPipeline.pas
ren GisPipelineOperations.pas Lider.CG.GIS.GeoPipelineOperations.pas
ren GisPixelFilter.pas Lider.CG.GIS.GeoPixelFilter.pas
ren GisPrintBuilder.pas Lider.CG.GIS.GeoPrintBuilder.pas
ren GisPrintUtils.pas Lider.CG.GIS.GeoPrintUtils.pas
ren GisRasterAlgebra.pas Lider.CG.GIS.GeoRasterAlgebra.pas
ren GisStatistics.pas Lider.CG.GIS.GeoStatistics.pas
ren GisTessellation.pas Lider.CG.GIS.GeoTessellation.pas
ren GisVectorization.pas Lider.CG.GIS.GeoVectorization.pas
ren PVL.GisControlBitmap.pas Lider.CG.GIS.PVL.GeoControlBitmap.pas
ren PVL.GisControlColor.pas Lider.CG.GIS.PVL.GeoControlColor.pas
ren PVL.GisControlFont.pas Lider.CG.GIS.PVL.GeoControlFont.pas
ren PVL.GisControlLegendGridWiz.pas Lider.CG.GIS.PVL.GeoControlLegendGridWiz.pas
ren PVL.GisControlLegendVectorWiz.pas Lider.CG.GIS.PVL.GeoControlLegendVectorWiz.pas
ren PVL.GisControlStatistics.pas Lider.CG.GIS.PVL.GeoControlStatistics.pas
ren PVL.GisControlSymbology.pas Lider.CG.GIS.PVL.GeoControlSymbology.pas
ren PVL.GisControlSymbologyLibrary.pas Lider.CG.GIS.PVL.GeoControlSymbologyLibrary.pas
ren VCL.GisControlFontStyleForm.pas Lider.CG.GIS.VCL.GeoControlFontStyleForm.pas
ren VCL.GisControlPrintPositionForm.pas Lider.CG.GIS.VCL.GeoControlPrintPositionForm.pas
ren VCL.GisFormPvl.pas Lider.CG.GIS.VCL.GeoFormPvl.pas
ren VCL.GisModalWizardPvl.pas Lider.CG.GIS.VCL.GeoModalWizardPvl.pas
ren VCL.GisPipelineParamsEditor.pas Lider.CG.GIS.VCL.GeoPipelineParamsEditor.pas
ren VCL.GisPrintTemplateDesigner.pas Lider.CG.GIS.VCL.GeoPrintTemplateDesigner.pas

ren FMX.GisPvlForms.pas Lider.CG.GIS.FMX.GeoPvlForms.pas
ren FMX.GisSystemForms.pas Lider.CG.GIS.FMX.GeoSystemForms.pas
ren PVL.GisPvlForms.pas Lider.CG.GIS.PVL.GeoPvlForms.pas
ren PVL.GisPvlWidgets.pas Lider.CG.GIS.PVL.GeoPvlWidgets.pas
ren VCL.GisPvlForms.pas Lider.CG.GIS.VCL.GeoPvlForms.pas
ren VCL.GisSystemForms.pas Lider.CG.GIS.VCL.GeoSystemForms.pas

ren FMX.AllPvl.pas Lider.CG.GIS.FMX.AllPvl.pas
ren FMX.GisPvlControl3D.pas Lider.CG.GIS.FMX.GeoPvlControl3D.pas
ren FMX.GisPvlControlAttributes.pas Lider.CG.GIS.FMX.GeoPvlControlAttributes.pas
ren FMX.GisPvlControlLegend.pas Lider.CG.GIS.FMX.GeoPvlControlLegend.pas
ren FMX.GisPvlControlNorthArrow.pas Lider.CG.GIS.FMX.GeoPvlControlNorthArrow.pas
ren FMX.GisPvlControlPrintPreview.pas Lider.CG.GIS.FMX.GeoPvlControlPrintPreview.pas
ren FMX.GisPvlControlScale.pas Lider.CG.GIS.FMX.GeoPvlControlScale.pas
ren FMX.GisPvlGrid.pas Lider.CG.GIS.FMX.GeoPvlGrid.pas
ren FMX.GisPvlViewerBmp.pas Lider.CG.GIS.FMX.GeoPvlViewerBmp.pas
ren FMX.GisPvlViewerWnd.pas Lider.CG.GIS.FMX.GeoPvlViewerWnd.pas
ren FMX.GisStyleRenderer.pas Lider.CG.GIS.FMX.GeoStyleRenderer.pas
ren GisAsyncRunner.pas Lider.CG.GIS.GeoAsyncRunner.pas
ren GisEditorTools.pas Lider.CG.GIS.GeoEditorTools.pas
ren GisStyleRendererAbstract.pas Lider.CG.GIS.GeoStyleRendererAbstract.pas
ren GisTilerHelper.pas Lider.CG.GIS.GeoTilerHelper.pas
ren PVL.GisControl3D.pas Lider.CG.GIS.PVL.GeoControl3D.pas
ren PVL.GisControlAttributes.pas Lider.CG.GIS.PVL.GeoControlAttributes.pas
ren PVL.GisControlLegend.pas Lider.CG.GIS.PVL.GeoControlLegend.pas
ren PVL.GisControlNorthArrow.pas Lider.CG.GIS.PVL.GeoControlNorthArrow.pas
ren PVL.GisControlPrintPreview.pas Lider.CG.GIS.PVL.GeoControlPrintPreview.pas
ren PVL.GisControlScale.pas Lider.CG.GIS.PVL.GeoControlScale.pas
ren PVL.GisGrid.pas Lider.CG.GIS.PVL.GeoGrid.pas
ren PVL.GisViewerBmp.pas Lider.CG.GIS.PVL.GeoViewerBmp.pas
ren PVL.GisViewerWnd.pas Lider.CG.GIS.PVL.GeoViewerWnd.pas
ren VCL.AllPvl.pas Lider.CG.GIS.VCL.AllPvl.pas
ren VCL.GisPvlControl3D.pas Lider.CG.GIS.VCL.GeoPvlControl3D.pas
ren VCL.GisPvlControlAttributes.pas Lider.CG.GIS.VCL.GeoPvlControlAttributes.pas
ren VCL.GisPvlControlLegend.pas Lider.CG.GIS.VCL.GeoPvlControlLegend.pas
ren VCL.GisPvlControlNorthArrow.pas Lider.CG.GIS.VCL.GeoPvlControlNorthArrow.pas
ren VCL.GisPvlControlPrintPreview.pas Lider.CG.GIS.VCL.GeoPvlControlPrintPreview.pas
ren VCL.GisPvlControlScale.pas Lider.CG.GIS.VCL.GeoPvlControlScale.pas
ren VCL.GisPvlGrid.pas Lider.CG.GIS.VCL.GeoPvlGrid.pas
ren VCL.GisPvlViewerBmp.pas Lider.CG.GIS.VCL.GeoPvlViewerBmp.pas
ren VCL.GisPvlViewerWnd.pas Lider.CG.GIS.VCL.GeoPvlViewerWnd.pas
ren VCL.GisRendererSkia.Common.pas Lider.CG.GIS.VCL.GeoRendererSkia.Common.pas
ren VCL.GisRendererSkia.pas Lider.CG.GIS.VCL.GeoRendererSkia.pas
ren VCL.GisRendererSkia.Stub.pas Lider.CG.GIS.VCL.GeoRendererSkia.Stub.pas
ren VCL.GisStyleRenderer.pas Lider.CG.GIS.VCL.GeoStyleRenderer.pas


