//=============================================================================
// This source code is a part of TatukGIS Developer Kernel.
// DK11.85.0.33382-Unstable2
// (c)2000-2023 TatukGIS. ALL RIGHTS RESERVED.
//
// This file is uniquely watermarked for licensed user:
// 
// Any unauthorized use this file can be traced back to the licensed user,
// who may be held accountable.
//=============================================================================
{
  List of Geographic Coordinate Systems.
  Extra ESRI compatible definitions.
  Generated automatically.
}


procedure Init_CSGeographicCoordinateSystemList2(
  const _cs : TGIS_CSGeographicCoordinateSystemList
) ;

procedure prepare_1;
begin
  _cs.AddAlias(  37001, 'WGS_1966',
                         4760
              );
  _cs.Add     (  37002, 'Fischer_1960',
                         906002, 8901, 9122
              );
  _cs.Add     (  37003, 'Fischer_1968',
                         906003, 8901, 9122
              );
  _cs.Add     (  37004, 'Fischer_Modified',
                         906004, 8901, 9122
              );
  _cs.Add     (  37005, 'Hough_1960',
                         906005, 8901, 9122
              );
  _cs.Add     (  37006, 'Everest_Modified_1969',
                         906006, 8901, 9122
              );
  _cs.Add     (  37007, 'Walbeck',
                         906007, 8901, 9122
              );
  _cs.AddAlias(  37201, 'European_1979',
                         4668
              );
  _cs.Add     (  37202, 'Everest_Bangladesh',
                         906202, 8901, 9122
              );
  _cs.Add     (  37203, 'Everest_India_Nepal',
                         906203, 8901, 9122
              );
  _cs.AddAlias(  37204, 'Hjorsey_1955',
                         4658
              );
  _cs.AddAlias(  37205, 'Hong_Kong_1963',
                         4739
              );
  _cs.Add     (  37206, 'Oman',
                         906206, 8901, 9122
              );
  _cs.Add     (  37207, 'South_Asia_Singapore',
                         906207, 8901, 9122
              );
  _cs.AddAlias(  37208, 'Ayabelle',
                         4713
              );
  _cs.AddAlias(  37211, 'Point_58',
                         4620
              );
  _cs.Add     (  37212, 'Beacon_E_1945',
                         906212, 8901, 9122
              );
  _cs.AddAlias(  37213, 'Tern_Island_1961',
                         4707
              );
  _cs.Add     (  37214, 'Astro_1952',
                         906214, 8901, 9122
              );
  _cs.AddAlias(  37215, 'Bellevue_IGN',
                         4714
              );
  _cs.Add     (  37216, 'Canton_1966',
                         906216, 8901, 9122
              );
  _cs.AddAlias(  37217, 'Chatham_Island_1971',
                         4672
              );
  _cs.Add     (  37218, 'DOS_1968',
                         906218, 8901, 9122
              );
  _cs.AddAlias(  37219, 'Easter_Island_1967',
                         4719
              );
  _cs.AddAlias(  37220, 'Guam_1963',
                         4675
              );
  _cs.Add     (  37221, 'GUX_1',
                         906221, 8901, 9122
              );
  _cs.AddAlias(  37222, 'Johnston_Island_1961',
                         4725
              );
  _cs.AddAlias(  37223, 'Carthage_Degree',
                         4223
              );
  _cs.AddAlias(  37224, 'Midway_1961',
                         4727
              );
  _cs.AddAlias(  37226, 'Pitcairn_1967',
                         4729
              );
  _cs.AddAlias(  37227, 'Santo_DOS_1965',
                         4730
              );
  _cs.AddAlias(  37228, 'Viti_Levu_1916',
                         4731
              );
  _cs.Add     (  37229, 'Wake_Eniwetok_1960',
                         906229, 8901, 9122
              );
  _cs.AddAlias(  37230, 'Wake_Island_1952',
                         4733
              );
  _cs.Add     (  37231, 'Anna_1_1965',
                         906231, 8901, 9122
              );
  _cs.AddAlias(  37232, 'Gan_1970',
                         4684
              );
  _cs.Add     (  37233, 'ISTS_073_1969',
                         906233, 8901, 9122
              );
  _cs.Add     (  37234, 'Kerguelen_Island_1949',
                         906234, 8901, 9122
              );
  _cs.Add     (  37235, 'Reunion',
                         906235, 8901, 9122
              );
  _cs.AddAlias(  37237, 'Ascension_Island_1958',
                         4712
              );
  _cs.Add     (  37238, 'DOS_71_4',
                         906238, 8901, 9122
              );
  _cs.AddAlias(  37239, 'Cape_Canaveral',
                         4717
              );
  _cs.Add     (  37240, 'Fort_Thomas_1955',
                         906240, 8901, 9122
              );
  _cs.Add     (  37241, 'Graciosa_Base_SW_1948',
                         906241, 8901, 9122
              );
  _cs.Add     (  37242, 'ISTS_061_1968',
                         906242, 8901, 9122
              );
  _cs.Add     (  37243, 'LC5_1961',
                         906243, 8901, 9122
              );
  _cs.Add     (  37245, 'Observ_Meteorologico_1939',
                         906245, 8901, 9122
              );
  _cs.AddAlias(  37246, 'Pico_de_Las_Nieves',
                         4022
              );
  _cs.AddAlias(  37247, 'Porto_Santo_1936',
                         4615
              );
  _cs.Add     (  37249, 'Sao_Braz',
                         906249, 8901, 9122
              );
  _cs.AddAlias(  37250, 'Selvagem_Grande_1938',
                         4616
              );
  _cs.AddAlias(  37251, 'Tristan_1968',
                         4734
              );
  _cs.AddAlias(  37252, 'Samoa_1962',
                         4169
              );
  _cs.AddAlias(  37253, 'Camp_Area',
                         4715
              );
  _cs.AddAlias(  37254, 'Deception_Island',
                         4736
              );
  _cs.AddAlias(  37255, 'Gunung_Segara',
                         4613
              );
  _cs.Add     (  37257, 'S42_Hungary',
                         906257, 8901, 9122
              );
  _cs.AddAlias(  37259, 'Kusaie_1951',
                         4735
              );
  _cs.Add     (  37260, 'Alaskan_Islands',
                         906260, 8901, 9122
              );
  _cs.AddAlias( 104000, 'Assumed_Geographic_1',
                         4267
              );
  _cs.Add     ( 104101, 'Estonia_1937',
                         906101, 8901, 9122
              );
  _cs.Add     ( 104102, 'Hermannskogel',
                         906102, 8901, 9122
              );
  _cs.Add     ( 104103, 'Sierra_Leone_1960',
                         906103, 8901, 9122
              );
  _cs.AddAlias( 104104, 'Hong_Kong_1980',
                         4611
              );
  _cs.Add     ( 104105, 'Datum_Lisboa_Bessel',
                         906261, 8901, 9122
              );
  _cs.Add     ( 104106, 'Datum_Lisboa_Hayford',
                         906263, 8901, 9122
              );
  _cs.AddAlias( 104107, 'RGF_1993',
                         4171
              );
  _cs.AddAlias( 104108, 'NZGD_2000',
                         4167
              );
  _cs.AddAlias( 104261, 'Merchich_Degree',
                         4261
              );
  _cs.AddAlias( 104304, 'Voirol_1875_Degree',
                         4304
              );
  _cs.AddAlias( 104305, 'Voirol_Unifie_1960_Degree',
                         4307
              );
end;

begin
  prepare_1;
end;

//==================================== END ====================================

