//=============================================================================
// This source code is a part of TatukGIS Developer Kernel.
// DK11.85.0.33382-Unstable2+priv
// (c)2000-2023 TatukGIS. ALL RIGHTS RESERVED.
//=============================================================================

const GIS_VERSION   = '11.85.0.33382-Unstable2+priv';
const GIS_COPYRIGHT = '(c)2000-2023 TatukGIS. All Rights Reserved.';
const GIS_PRODUCTID = 'DK12.Delphi.RX12';


