//=============================================================================
// This source code is a part of TatukGIS Developer Kernel.
// DKv100.1.37476
// (c)2000-2025 TatukGIS. ALL RIGHTS RESERVED.
//
// This file is uniquely watermarked for licensed user:
// 
// Any unauthorized use this file can be traced back to the licensed user,
// who may be held accountable.
//=============================================================================
{
  List of Areas.
  User defined list.
  New items should be defined as 907xxx.
}


procedure Init_CSAreaListEx(
  const _cs : TGIS_CSAreaList
) ;

procedure prepare_1;
begin
  _cs.Add     ( 907024, _rsrc( GIS_RS_EPSG_907024 )
              ) ;
  _cs.Add     ( 907025, _rsrc( GIS_RS_EPSG_907025 )
              ) ;
  _cs.Add     ( 907026, _rsrc( GIS_RS_EPSG_907026 )
              ) ;
  _cs.Add     ( 907027, _rsrc( GIS_RS_EPSG_907027 )
              ) ;
  _cs.Add     ( 907028, _rsrc( GIS_RS_EPSG_907028 )
              ) ;
  _cs.Add     ( 907029, _rsrc( GIS_RS_EPSG_907029 )
              ) ;
  _cs.Add     ( 907030, _rsrc( GIS_RS_EPSG_907030 )
              ) ;
  _cs.Add     ( 907031, _rsrc( GIS_RS_EPSG_907031 )
              ) ;
  _cs.Add     ( 907032, _rsrc( GIS_RS_EPSG_907032 )
              ) ;
  _cs.Add     ( 907033, _rsrc( GIS_RS_EPSG_907033 )
              ) ;
  _cs.Add     ( 907034, _rsrc( GIS_RS_EPSG_907034 )
              ) ;
  _cs.Add     ( 907035, _rsrc( GIS_RS_EPSG_907035 )
              ) ;
  _cs.Add     ( 907036, _rsrc( GIS_RS_EPSG_907036 )
              ) ;
  _cs.Add     ( 907037, _rsrc( GIS_RS_EPSG_907037 )
              ) ;
  _cs.Add     ( 907038, _rsrc( GIS_RS_EPSG_907038 )
              ) ;
  _cs.Add     ( 907039, _rsrc( GIS_RS_EPSG_907039 )
              ) ;
  _cs.Add     ( 907040, _rsrc( GIS_RS_EPSG_907040 )
              ) ;
  _cs.Add     ( 907041, _rsrc( GIS_RS_EPSG_907041 )
              ) ;
  _cs.Add     ( 907042, _rsrc( GIS_RS_EPSG_907042 )
              ) ;
  _cs.Add     ( 907043, _rsrc( GIS_RS_EPSG_907043 )
              ) ;
  _cs.Add     ( 901044, _rsrc( GIS_RS_EPSG_901044 )
              ) ;
  _cs.Add     ( 907045, _rsrc( GIS_RS_EPSG_907045 )
              ) ;
  _cs.Add     ( 907046, _rsrc( GIS_RS_EPSG_907046 )
              ) ;
  _cs.Add     ( 907047, _rsrc( GIS_RS_EPSG_907047 )
              ) ;
  _cs.Add     ( 907048, _rsrc( GIS_RS_EPSG_907048 )
              ) ;
end;

begin
  prepare_1;

end;
{==================================== END =====================================}


