//=============================================================================
// This source code is a part of TatukGIS Developer Kernel.
// DKv100.1.37476
// (c)2000-2025 TatukGIS. ALL RIGHTS RESERVED.
//
// This file is uniquely watermarked for licensed user:
// ILKER#LIDERYAZILIM.COM-481078-KSVX7UYN-1D12B8B5
// Any unauthorized use this file can be traced back to the licensed user,
// who may be held accountable.
//=============================================================================
{
  List of Datums.
  Matching ESRI names and EPSG codes.
  Generated automatically.
}


procedure Init_ESRIDatumList(
  const _cs : T_esriNamesMap
) ;

procedure prepare_1;
begin
  _cs.Add     (    1024, 'D_Hungarian_Datum_1909'
              );
  _cs.Add     (    1029, 'D_Iraqi_Geospatial_Reference_System'
              );
  _cs.Add     (    1031, 'D_MGI_1901'
              );
  _cs.Add     (    1032, 'D_MOLDREF99'
              );
  _cs.Add     (    1037, 'D_Cadastre_1997'
              );
  _cs.Add     (    1042, 'D_Mexican_Datum_of_1993'
              );
  _cs.Add     (    1043, 'D_China_2000'
              );
  _cs.Add     (    1056, 'D_GDBD2009'
              );
  _cs.Add     (    1058, 'D_Bhutan_National_Geodetic_Datum'
              );
  _cs.Add     (    1060, 'D_Islands_Network_2004'
              );
  _cs.Add     (    1061, 'D_ITRF_2008'
              );
  _cs.Add     (    1063, 'D_Marco_Geodesico_Nacional'
              );
  _cs.Add     (    1065, 'D_Costa_Rica_2005'
              );
  _cs.Add     (    1074, 'D_Corrego_Alegre_1961'
              );
  _cs.Add     (    6001, 'D_Airy_1830'
              );
  _cs.Add     (    6002, 'D_Airy_Modified'
              );
  _cs.Add     (    6003, 'D_Australian'
              );
  _cs.Add     (    6004, 'D_Bessel_1841'
              );
  _cs.Add     (    6005, 'D_Bessel_Modified'
              );
  _cs.Add     (    6006, 'D_Bessel_Namibia'
              );
  _cs.Add     (    6007, 'D_Clarke_1858'
              );
  _cs.Add     (    6008, 'D_Clarke_1866'
              );
  _cs.Add     (    6009, 'D_Clarke_1866_Michigan'
              );
  _cs.Add     (    6010, 'D_Clarke_1880_Benoit'
              );
  _cs.Add     (    6011, 'D_Clarke_1880_IGN'
              );
  _cs.Add     (    6012, 'D_Clarke_1880_RGS'
              );
  _cs.Add     (    6013, 'D_Clarke_1880_Arc'
              );
  _cs.Add     (    6014, 'D_Clarke_1880_SGA'
              );
  _cs.Add     (    6015, 'D_Everest_Adj_1937'
              );
  _cs.Add     (    6016, 'D_Everest_Def_1967'
              );
  _cs.Add     (    6018, 'D_Everest_Modified'
              );
  _cs.Add     (    6019, 'D_GRS_1980'
              );
  _cs.Add     (    6020, 'D_Helmert_1906'
              );
  _cs.Add     (    6021, 'D_Indonesian'
              );
  _cs.Add     (    6022, 'D_International_1924'
              );
  _cs.Add     (    6024, 'D_Krasovsky_1940'
              );
  _cs.Add     (    6031, 'D_GEM_10C'
              );
  _cs.Add     (    6034, 'D_Clarke_1880'
              );
  _cs.Add     (    6036, 'D_GRS_1967'
              );
  _cs.Add     (    6042, 'D_Everest_1830'
              );
  _cs.Add     (    6044, 'D_Everest_Def_1962'
              );
  _cs.Add     (    6045, 'D_Everest_Def_1975'
              );
  _cs.Add     (    6054, 'D_Hughes_1980'
              );
  _cs.Add     (    6120, 'D_Greek'
              );
  _cs.Add     (    6121, 'D_GGRS_1987'
              );
  _cs.Add     (    6122, 'D_ATS_1977'
              );
  _cs.Add     (    6123, 'D_KKJ'
              );
  _cs.Add     (    6126, 'D_Lithuania_1994'
              );
  _cs.Add     (    6128, 'D_Madzansua'
              );
  _cs.Add     (    6130, 'D_Moznet'
              );
  _cs.Add     (    6131, 'D_Indian_1960'
              );
  _cs.Add     (    6132, 'D_FD_1958'
              );
  _cs.Add     (    6133, 'D_Estonia_1992'
              );
  _cs.Add     (    6141, 'D_Israel'
              );
  _cs.Add     (    6142, 'D_Locodjo_1965'
              );
  _cs.Add     (    6143, 'D_Abidjan_1987'
              );
  _cs.Add     (    6144, 'D_Kalianpur_1937'
              );
  _cs.Add     (    6145, 'D_Kalianpur_1962'
              );
  _cs.Add     (    6146, 'D_Kalianpur_1975'
              );
  _cs.Add     (    6147, 'D_Hanoi_1972'
              );
  _cs.Add     (    6148, 'D_Hartebeesthoek_1994'
              );
  _cs.Add     (    6149, 'D_CH1903'
              );
  _cs.Add     (    6150, 'D_CH1903+'
              );
  _cs.Add     (    6154, 'D_European_1950_ED77'
              );
  _cs.Add     (    6155, 'D_Dabola_1981'
              );
  _cs.Add     (    6157, 'D_Mount_Dillon'
              );
  _cs.Add     (    6159, 'D_European_Libyan_1979'
              );
  _cs.Add     (    6160, 'D_Chos_Malal_1914'
              );
  _cs.Add     (    6162, 'D_Korean_Datum_1985'
              );
  _cs.Add     (    6165, 'D_Bissau'
              );
  _cs.Add     (    6166, 'D_Korean_Datum_1995'
              );
  _cs.Add     (    6168, 'D_Accra'
              );
  _cs.Add     (    6169, 'D_American_Samoa_1962'
              );
  _cs.Add     (    6173, 'D_IRENET95'
              );
  _cs.Add     (    6176, 'D_Australian_Antarctic_1998'
              );
  _cs.Add     (    6180, 'D_Estonia_1997'
              );
  _cs.Add     (    6181, 'D_Luxembourg_1930'
              );
  _cs.Add     (    6182, 'D_Azores_Occidental_Islands_1939'
              );
  _cs.Add     (    6183, 'D_Azores_Central_Islands_1948'
              );
  _cs.Add     (    6184, 'D_Azores_Oriental_Islands_1940'
              );
  _cs.Add     (    6185, 'D_Madeira_1936'
              );
  _cs.Add     (    6191, 'D_Albanian_1987'
              );
  _cs.Add     (    6192, 'D_Douala_1948'
              );
  _cs.Add     (    6193, 'D_Manoca_1962'
              );
  _cs.Add     (    6196, 'D_Ammassalik_1958'
              );
  _cs.Add     (    6198, 'D_Kousseri'
              );
  _cs.Add     (    6199, 'D_Egypt_1930'
              );
  _cs.Add     (    6201, 'D_Adindan'
              );
  _cs.Add     (    6202, 'D_Australian_1966'
              );
  _cs.Add     (    6203, 'D_Australian_1984'
              );
  _cs.Add     (    6204, 'D_Ain_el_Abd_1970'
              );
  _cs.Add     (    6205, 'D_Afgooye'
              );
  _cs.Add     (    6206, 'D_Agadez'
              );
  _cs.Add     (    6207, 'D_Lisbon'
              );
  _cs.Add     (    6208, 'D_Aratu'
              );
  _cs.Add     (    6209, 'D_Arc_1950'
              );
  _cs.Add     (    6210, 'D_Arc_1960'
              );
  _cs.Add     (    6211, 'D_Batavia'
              );
  _cs.Add     (    6212, 'D_Barbados_1938'
              );
  _cs.Add     (    6213, 'D_Beduaram'
              );
end;

procedure prepare_2;
begin
  _cs.Add     (    6214, 'D_Beijing_1954'
              );
  _cs.Add     (    6215, 'D_Belge_1950'
              );
  _cs.Add     (    6216, 'D_Bermuda_1957'
              );
  _cs.Add     (    6218, 'D_Bogota'
              );
  _cs.Add     (    6219, 'D_Bukit_Rimpah'
              );
  _cs.Add     (    6220, 'D_Camacupa'
              );
  _cs.Add     (    6221, 'D_Campo_Inchauspe'
              );
  _cs.Add     (    6222, 'D_Cape'
              );
  _cs.Add     (    6223, 'D_Carthage'
              );
  _cs.Add     (    6224, 'D_Chua'
              );
  _cs.Add     (    6225, 'D_Corrego_Alegre'
              );
  _cs.Add     (    6226, 'D_Cote_d_Ivoire'
              );
  _cs.Add     (    6227, 'D_Deir_ez_Zor'
              );
  _cs.Add     (    6228, 'D_Douala'
              );
  _cs.Add     (    6229, 'D_Egypt_1907'
              );
  _cs.Add     (    6230, 'D_European_1950'
              );
  _cs.Add     (    6231, 'D_European_1987'
              );
  _cs.Add     (    6232, 'D_Fahud'
              );
  _cs.Add     (    6234, 'D_Garoua'
              );
  _cs.Add     (    6235, 'D_Guyane_Francaise'
              );
  _cs.Add     (    6236, 'D_Hu_Tzu_Shan'
              );
  _cs.Add     (    6237, 'D_Hungarian_1972'
              );
  _cs.Add     (    6238, 'D_Indonesian_1974'
              );
  _cs.Add     (    6239, 'D_Indian_1954'
              );
  _cs.Add     (    6240, 'D_Indian_1975'
              );
  _cs.Add     (    6241, 'D_Jamaica_1875'
              );
  _cs.Add     (    6242, 'D_Jamaica_1969'
              );
  _cs.Add     (    6243, 'D_Kalianpur_1880'
              );
  _cs.Add     (    6244, 'D_Kandawala'
              );
  _cs.Add     (    6245, 'D_Kertau'
              );
  _cs.Add     (    6246, 'D_Kuwait_Oil_Company'
              );
  _cs.Add     (    6247, 'D_La_Canoa'
              );
  _cs.Add     (    6249, 'D_Lake'
              );
  _cs.Add     (    6250, 'D_Leigon'
              );
  _cs.Add     (    6251, 'D_Liberia_1964'
              );
  _cs.Add     (    6252, 'D_Lome'
              );
  _cs.Add     (    6253, 'D_Luzon_1911'
              );
  _cs.Add     (    6254, 'D_Hito_XVIII_1963'
              );
  _cs.Add     (    6255, 'D_Herat_North'
              );
  _cs.Add     (    6256, 'D_Mahe_1971'
              );
  _cs.Add     (    6257, 'D_Makassar'
              );
  _cs.Add     (    6258, 'D_ETRS_1989'
              );
  _cs.Add     (    6259, 'D_Malongo_1987'
              );
  _cs.Add     (    6260, 'D_Manoca'
              );
  _cs.Add     (    6261, 'D_Merchich'
              );
  _cs.Add     (    6262, 'D_Massawa'
              );
  _cs.Add     (    6263, 'D_Minna'
              );
  _cs.Add     (    6265, 'D_Monte_Mario'
              );
  _cs.Add     (    6266, 'D_Mporaloko'
              );
  _cs.Add     (    6274, 'D_Datum_73'
              );
  _cs.Add     (    6283, 'D_GDA_1994'
              );
  _cs.Add     (    6288, 'D_Loma_Quintana'
              );
  _cs.Add     (    6289, 'D_Amersfoort'
              );
  _cs.Add     (    6306, 'D_Bern_1938'
              );
  _cs.Add     (    6312, 'D_MGI'
              );
  _cs.Add     (    6313, 'D_Belge_1972'
              );
  _cs.Add     (    6314, 'D_Deutsches_Hauptdreiecksnetz'
              );
  _cs.Add     (    6315, 'D_Conakry_1905'
              );
  _cs.Add     (    6316, 'D_Dealul_Piscului_1933'
              );
  _cs.Add     (    6317, 'D_Dealul_Piscului_1970'
              );
  _cs.Add     (    6319, 'D_Kuwait_Utility'
              );
  _cs.Add     (    6600, 'D_Anguilla_1957'
              );
  _cs.Add     (    6601, 'D_Antigua_1943'
              );
  _cs.Add     (    6602, 'D_Dominica_1945'
              );
  _cs.Add     (    6603, 'D_Grenada_1953'
              );
  _cs.Add     (    6604, 'D_Montserrat_1958'
              );
  _cs.Add     (    6608, 'D_NAD_1927_Definition_1976'
              );
  _cs.Add     (    6609, 'D_NAD_1927_CGQ77'
              );
  _cs.Add     (    6611, 'D_Hong_Kong_1980'
              );
  _cs.Add     (    6612, 'D_JGD_2000'
              );
  _cs.Add     (    6613, 'D_Gunung_Segara'
              );
  _cs.Add     (    6621, 'D_Fort_Marigot'
              );
  _cs.Add     (    6623, 'D_CSG_1967'
              );
  _cs.Add     (    6625, 'D_Fort_Desaix'
              );
  _cs.Add     (    6630, 'D_IGN72_Nuku_Hiva'
              );
  _cs.Add     (    6632, 'D_Combani_1950'
              );
  _cs.Add     (    6633, 'D_IGN56_Lifou'
              );
  _cs.Add     (    6634, 'D_IGN72_Grande_Terre'
              );
  _cs.Add     (    6639, 'D_MOP78'
              );
  _cs.Add     (    6641, 'D_IGN53_Mare'
              );
  _cs.Add     (    6646, 'D_Grand_Comoros'
              );
  _cs.Add     (    6647, 'D_ITRF_1988'
              );
  _cs.Add     (    6648, 'D_ITRF_1989'
              );
  _cs.Add     (    6649, 'D_ITRF_1990'
              );
  _cs.Add     (    6650, 'D_ITRF_1991'
              );
  _cs.Add     (    6651, 'D_ITRF_1992'
              );
  _cs.Add     (    6652, 'D_ITRF_1993'
              );
  _cs.Add     (    6653, 'D_ITRF_1994'
              );
  _cs.Add     (    6654, 'D_ITRF_1996'
              );
  _cs.Add     (    6655, 'D_ITRF_1997'
              );
  _cs.Add     (    6656, 'D_ITRF_2000'
              );
  _cs.Add     (    6658, 'D_Hjorsey_1955'
              );
  _cs.Add     (    6659, 'D_Islands_Network_1993'
              );
  _cs.Add     (    6660, 'D_Helle_1954'
              );
  _cs.Add     (    6661, 'D_Latvia_1992'
              );
  _cs.Add     (    6664, 'D_Azores_Oriental_Islands_1995'
              );
  _cs.Add     (    6665, 'D_Azores_Central_Islands_1995'
              );
  _cs.Add     (    6666, 'D_Lisbon_1890'
              );
  _cs.Add     (    6667, 'D_Iraq_Kuwait_Boundary_1992'
              );
  _cs.Add     (    6668, 'D_European_1979'
              );
end;

procedure prepare_3;
begin
  _cs.Add     (    6670, 'D_IGM_1995'
              );
  _cs.Add     (    6672, 'D_Chatham_Island_1971'
              );
  _cs.Add     (    6673, 'D_Chatham_Islands_1979'
              );
  _cs.Add     (    6675, 'D_Guam_1963'
              );
  _cs.Add     (    6677, 'D_Lao_1993'
              );
  _cs.Add     (    6678, 'D_Lao_National_Datum_1997'
              );
  _cs.Add     (    6679, 'D_Jouik_1961'
              );
  _cs.Add     (    6682, 'D_Gulshan_303'
              );
  _cs.Add     (    6684, 'D_Gan_1970'
              );
  _cs.Add     (    6686, 'D_MAGNA'
              );
  _cs.Add     (    6688, 'D_Fatu_Iva_1972'
              );
  _cs.Add     (    6689, 'D_IGN63_Hiva_Oa'
              );
  _cs.Add     (    6691, 'D_Moorea_1987'
              );
  _cs.Add     (    6692, 'D_Maupiti_1983'
              );
  _cs.Add     (    6695, 'D_Katanga_1955'
              );
  _cs.Add     (    6696, 'D_Kasai_1953'
              );
  _cs.Add     (    6697, 'D_IGC_1962_Arc_of_the_6th_Parallel_South'
              );
  _cs.Add     (    6698, 'D_Kerguelen_Island_1949'
              );
  _cs.Add     (    6699, 'D_Le_Pouce_1934'
              );
  _cs.Add     (    6700, 'D_IGN_Astro_1960'
              );
  _cs.Add     (    6701, 'D_Institut_Geographique_du_Congo_Belge_1955'
              );
  _cs.Add     (    6702, 'D_Mauritania_1999'
              );
  _cs.Add     (    6703, 'D_Mhast_1951'
              );
  _cs.Add     (    6704, 'D_Mhast_Onshore'
              );
  _cs.Add     (    6705, 'D_Mhast_Offshore'
              );
  _cs.Add     (    6706, 'D_Egypt_Gulf_of_Suez_S_650_TL'
              );
  _cs.Add     (    6708, 'D_Anna_1_1965'
              );
  _cs.Add     (    6709, 'D_Beacon_E_1945'
              );
  _cs.Add     (    6710, 'D_DOS_71_4'
              );
  _cs.Add     (    6711, 'D_Astro_1952'
              );
  _cs.Add     (    6712, 'D_Ascension_Island_1958'
              );
  _cs.Add     (    6713, 'D_Ayabelle'
              );
  _cs.Add     (    6714, 'D_Bellevue_IGN'
              );
  _cs.Add     (    6715, 'D_Camp_Area'
              );
  _cs.Add     (    6716, 'D_Canton_1966'
              );
  _cs.Add     (    6717, 'D_Cape_Canaveral'
              );
  _cs.Add     (    6719, 'D_Easter_Island_1967'
              );
  _cs.Add     (    6720, 'D_Fiji_1986'
              );
  _cs.Add     (    6721, 'D_Fiji_1956'
              );
  _cs.Add     (    6722, 'D_ISTS_061_1968'
              );
  _cs.Add     (    6723, 'D_Grand_Cayman_1959'
              );
  _cs.Add     (    6724, 'D_ISTS_073_1969'
              );
  _cs.Add     (    6725, 'D_Johnston_Island_1961'
              );
  _cs.Add     (    6726, 'D_Little_Cayman_1961'
              );
  _cs.Add     (    6727, 'D_Midway_1961'
              );
  _cs.Add     (    6735, 'D_Kusaie_1951'
              );
  _cs.Add     (    6736, 'D_Deception_Island'
              );
  _cs.Add     (    6737, 'D_Korea_2000'
              );
  _cs.Add     (    6738, 'D_Hong_Kong_1963'
              );
  _cs.Add     (    6739, 'D_Hong_Kong_1963_67'
              );
  _cs.Add     (    6741, 'D_Faroe_Datum_1954'
              );
  _cs.Add     (    6742, 'D_GDM_2000'
              );
  _cs.Add     (    6743, 'D_Karbala_1979_Polservice'
              );
  _cs.Add     (    6747, 'D_Greenland_1996'
              );
  _cs.Add     (    6751, 'D_Kertau_RSO'
              );
  _cs.Add     (    6753, 'D_fk89'
              );
  _cs.Add     (    6754, 'D_Libyan_Geodetic_Datum_2006'
              );
  _cs.Add     (    6755, 'D_Datum_Geodesi_Nasional_1995'
              );
  _cs.Add     (    6758, 'D_Jamaica_2001'
              );
  _cs.Add     (    6761, 'D_Croatian_Terrestrial_Reference_System'
              );
  _cs.Add     (    6762, 'D_Bermuda_2000'
              );
  _cs.Add     (    6896, 'D_ITRF_2005'
              );
  _cs.Add     (    6901, 'D_ATF'
              );
  _cs.Add     (    6903, 'D_Madrid_1870'
              );
end;

begin
  prepare_1;
  prepare_2;
  prepare_3;
end;

//==================================== END ====================================

