//=============================================================================
// This source code is a part of TatukGIS Developer Kernel.
// DKv100.1.37476
// (c)2000-2025 TatukGIS. ALL RIGHTS RESERVED.
//
// This file is uniquely watermarked for licensed user:
// ILKER#LIDERYAZILIM.COM-481078-KSVX7UYN-1D12B8B5
// Any unauthorized use this file can be traced back to the licensed user,
// who may be held accountable.
//=============================================================================
{
  Map between ECW Geographic Coordinate Systems.
  Generated automatically.
}


procedure Init_ECWGeographicCoordinateSystemList(
  const _cs : T_gcsMap
) ;

procedure prepare_1;
begin
  _cs.Add     (   4168, 'ACCRA',
                        '', 0, 0
              );
  _cs.Add     (   4201, 'ADINDAN',
                        '', 0, 0
              );
  _cs.Add     (   4202, 'AGD66',
                        '', 0, 0
              );
  _cs.Add     (   4202, 'AGD66NTV',
                        '', 0, 0
              );
  _cs.Add     (   4203, 'AGD84',
                        '', 0, 0
              );
  _cs.Add     (   4204, 'AINABD70',
                        '', 0, 0
              );
  _cs.Add     (   4208, 'ARATU',
                        '', 0, 0
              );
  _cs.Add     (   4209, 'ARC1950',
                        '', 0, 0
              );
  _cs.Add     (   4210, 'ARC1960',
                        '', 0, 0
              );
  _cs.Add     (   4204, 'BAHRAIN',
                        '', 0, 0
              );
  _cs.Add     (   4211, 'BATAVIA',
                        '', 0, 0
              );
  _cs.Add     (   4213, 'BEDUARAM',
                        '', 0, 0
              );
  _cs.Add     (   4214, 'BEIJING',
                        '', 0, 0
              );
  _cs.Add     (   4215, 'BELG50',
                        '', 0, 0
              );
  _cs.Add     (   4801, 'BERNNEW',
                        '', 0, 0
              );
  _cs.Add     (   4218, 'BOGOTA',
                        '', 0, 0
              );
  _cs.Add     (   4220, 'CAMACUPA',
                        '', 0, 0
              );
  _cs.Add     (   4222, 'CAPE',
                        '', 0, 0
              );
  _cs.Add     (   4223, 'CARTHAGE',
                        '', 0, 0
              );
  _cs.Add     (   4224, 'CHUA',
                        '', 0, 0
              );
  _cs.Add     (   4008, 'CLRK1866',
                        '', 0, 0
              );
  _cs.Add     (   4221, 'CMPOINCH',
                        '', 0, 0
              );
  _cs.Add     (   4225, 'CORRALEG',
                        '', 0, 0
              );
  _cs.Add     (   4227, 'DEIR',
                        '', 0, 0
              );
  _cs.Add     (   4230, 'ED50',
                        '', 0, 0
              );
  _cs.Add     (   4022, 'ED50EGYT',
                        '', 0, 0
              );
  _cs.Add     (   4022, 'ED50SVAL',
                        '', 0, 0
              );
  _cs.Add     (   4022, 'EDMCE75',
                        '', 0, 0
              );
  _cs.Add     (   4121, 'EGSA87',
                        '', 0, 0
              );
  _cs.Add     (   4229, 'EGYPT07',
                        '', 0, 0
              );
  _cs.Add     (   4199, 'EGYPT24',
                        '', 0, 0
              );
  _cs.Add     (   4015, 'EVVIETNM',
                        '', 0, 0
              );
  _cs.Add     (   4232, 'FAHUD',
                        '', 0, 0
              );
  _cs.Add     (   4123, 'FINKKJ',
                        '', 0, 0
              );
  _cs.Add     (   4283, 'GDA94',
                        '', 0, 0
              );
  _cs.Add     (   4121, 'HGRS87',
                        '', 0, 0
              );
  _cs.Add     (   4611, 'HK80',
                        '', 0, 0
              );
  _cs.Add     (   4238, 'IND74',
                        '', 0, 0
              );
  _cs.Add     (   4239, 'INDIAN54',
                        '', 0, 0
              );
  _cs.Add     (   4131, 'INDIAN60',
                        '', 0, 0
              );
  _cs.Add     (   4240, 'INDIAN75',
                        '', 0, 0
              );
  _cs.Add     (   4281, 'ISRLURIM',
                        '', 0, 0
              );
  _cs.Add     (   4241, 'JA1875',
                        '', 0, 0
              );
  _cs.Add     (   4242, 'JAD69',
                        '', 0, 0
              );
  _cs.Add     (   4123, 'KKJ',
                        '', 0, 0
              );
  _cs.Add     (   4146, 'KALIANPR',
                        '', 0, 0
              );
  _cs.Add     (   4743, 'KARBALA',
                        '', 0, 0
              );
  _cs.Add     (   4245, 'KERTAU',
                        '', 0, 0
              );
  _cs.Add     (   4246, 'KOC',
                        '', 0, 0
              );
  _cs.Add     (   4166, 'KOREA',
                        '', 0, 0
              );
  _cs.Add     (   4247, 'LACANOA',
                        '', 0, 0
              );
  _cs.Add     (   4250, 'LEIGON',
                        '', 0, 0
              );
  _cs.Add     (   4022, 'LISBOA',
                        '', 0, 0
              );
  _cs.Add     (   4207, 'LISBON',
                        '', 0, 0
              );
  _cs.Add     ( 104105, 'LISBONBESSEL',
                        '', 0, 0
              );
  _cs.Add     (   4253, 'LUZON11',
                        '', 0, 0
              );
  _cs.Add     (   4256, 'MAHE71',
                        '', 0, 0
              );
  _cs.Add     (   4257, 'MAKASSAR',
                        '', 0, 0
              );
  _cs.Add     (   4704, 'MALONG79',
                        '', 0, 0
              );
  _cs.Add     (   4259, 'MALONG90',
                        '', 0, 0
              );
  _cs.Add     (   4260, 'MANOKA',
                        '', 0, 0
              );
  _cs.Add     (   4274, 'MELRICA',
                        '', 0, 0
              );
  _cs.Add     (   4312, 'MGIBESS',
                        '', 0, 0
              );
  _cs.Add     (   4263, 'MINAA',
                        '', 0, 0
              );
  _cs.Add     (   4265, 'MONTEMAR',
                        '', 0, 0
              );
  _cs.Add     (   4806, 'MONTROME',
                        '', 0, 0
              );
  _cs.Add     (   4266, 'MPORO',
                        '', 0, 0
              );
  _cs.Add     (   4267, 'NAD27',
                        '', 0, 0
              );
  _cs.Add     (   4008, 'NAD27A74',
                        '', 0, 0
              );
  _cs.Add     (   4608, 'NAD27A76',
                        '', 0, 0
              );
  _cs.Add     (   4267, 'NAD27AFT',
                        '', 0, 0
              );
  _cs.Add     (   4268, 'NAD27MOD',
                        '', 0, 0
              );
  _cs.Add     (   4267, 'NAD27MTR',
                        '', 0, 0
              );
  _cs.Add     (   4269, 'NAD83',
                        '', 0, 0
              );
  _cs.Add     (   4270, 'NAHRWAN',
                        '', 0, 0
              );
  _cs.Add     (   4006, 'NAMIBIA',
                        '', 0, 0
              );
  _cs.Add     (   4275, 'NTF',
                        '', 0, 0
              );
  _cs.Add     (   4807, 'NTFPARG',
                        '', 0, 0
              );
  _cs.Add     (   4807, 'NTFPARIS',
                        '', 0, 0
              );
  _cs.Add     (   4025, 'NWL9D',
                        '', 0, 0
              );
  _cs.Add     (   4272, 'NZGD49',
                        '', 0, 0
              );
  _cs.Add     (   4167, 'NZGD2000',
                        '', 0, 0
              );
  _cs.Add     (   4277, 'OSGB36',
                        '', 0, 0
              );
  _cs.Add     (   4278, 'OSGB70',
                        '', 0, 0
              );
  _cs.Add     (   4279, 'OSSN80',
                        '', 0, 0
              );
  _cs.Add     (   4280, 'PADANG',
                        '', 0, 0
              );
  _cs.Add     (   4281, 'PALEST23',
                        '', 0, 0
              );
  _cs.Add     (   4027, 'PLESSIS',
                        '', 0, 0
              );
  _cs.Add     (   4746, 'POTSDAM',
                        '', 0, 0
              );
  _cs.Add     (   4683, 'PRS92',
                        '', 0, 0
              );
  _cs.Add     (   4248, 'PSAD56',
                        '', 0, 0
              );
  _cs.Add     (   4282, 'PTNOIRE',
                        '', 0, 0
              );
  _cs.Add     (   4284, 'PULKOVO',
                        '', 0, 0
              );
  _cs.Add     (   4285, 'QATAR',
                        '', 0, 0
              );
  _cs.Add     (   4286, 'QATAR51',
                        '', 0, 0
              );
  _cs.Add     (   4287, 'QORNOQ',
                        '', 0, 0
              );
  _cs.Add     (   4289, 'RD',
                        '', 0, 0
              );
  _cs.Add     (   4171, 'RGF93',
                        '', 0, 0
              );
  _cs.Add     (   4291, 'SAD69',
                        '', 0, 0
              );
  _cs.Add     (     -1, 'SECLV',
                        'GRS_1967_Modified', 6378160, 298.25
              );
end;

procedure prepare_2;
begin
  _cs.Add     (   4765, 'SLOVENIA',
                        '', 0, 0
              );
  _cs.Add     (   4035, 'SPHERE',
                        '', 0, 0
              );
  _cs.Add     (     -1, 'SPHERE2',
                        'GRS_1980_Authalic_Sphere', 6370997, 0
              );
  _cs.Add     (   4296, 'SUDAN',
                        '', 0, 0
              );
  _cs.Add     (   4297, 'TANANAR',
                        '', 0, 0
              );
  _cs.Add     (   4810, 'TANANPAR',
                        '', 0, 0
              );
  _cs.Add     (   4298, 'TIMBALAI',
                        '', 0, 0
              );
  _cs.Add     (   4298, 'TIMBALFT',
                        '', 0, 0
              );
  _cs.Add     (   4299, 'TM65',
                        '', 0, 0
              );
  _cs.Add     (   4300, 'TM75',
                        '', 0, 0
              );
  _cs.Add     (   4301, 'TOKYO',
                        '', 0, 0
              );
  _cs.Add     (   4303, 'TRUCIAL',
                        '', 0, 0
              );
  _cs.Add     (   4002, 'USAIRMOD',
                        '', 0, 0
              );
  _cs.Add     (   4001, 'USAIRY',
                        '', 0, 0
              );
  _cs.Add     (   4003, 'USANS',
                        '', 0, 0
              );
  _cs.Add     (   4005, 'USBESMOD',
                        '', 0, 0
              );
  _cs.Add     (   4004, 'USBESS',
                        '', 0, 0
              );
  _cs.Add     (   4007, 'USC58MTR',
                        '', 0, 0
              );
  _cs.Add     (   4008, 'USC66AFT',
                        '', 0, 0
              );
  _cs.Add     (   4008, 'USC66MTR',
                        '', 0, 0
              );
  _cs.Add     (   4011, 'USC80IGN',
                        '', 0, 0
              );
  _cs.Add     (   4012, 'USC80MOD',
                        '', 0, 0
              );
  _cs.Add     (   4013, 'USC80RSA',
                        '', 0, 0
              );
  _cs.Add     (   4015, 'USEV37AD',
                        '', 0, 0
              );
  _cs.Add     (   4016, 'USEV67',
                        '', 0, 0
              );
  _cs.Add     (   4036, 'USGRS67',
                        '', 0, 0
              );
  _cs.Add     (   4019, 'USGRS80',
                        '', 0, 0
              );
  _cs.Add     (     -1, 'USHAYF10',
                        'HAYF1910', 6378388, 296.9592625
              );
  _cs.Add     (   4020, 'USHELM',
                        '', 0, 0
              );
  _cs.Add     (   4022, 'USINT24',
                        '', 0, 0
              );
  _cs.Add     (     -1, 'USINT67',
                        'GRS_1967_Modified', 6378160, 298.25
              );
  _cs.Add     (   4024, 'USKRAS40',
                        '', 0, 0
              );
  _cs.Add     (   4043, 'USNWL10D',
                        '', 0, 0
              );
  _cs.Add     (   4025, 'USNWL9D',
                        '', 0, 0
              );
  _cs.Add     (   4035, 'USSPHERE',
                        '', 0, 0
              );
  _cs.Add     (   4324, 'WGS72BE',
                        '', 0, 0
              );
  _cs.Add     (   4043, 'WGS72DOD',
                        '', 0, 0
              );
  _cs.Add     (   4326, 'WGS84',
                        '', 0, 0
              );
  _cs.Add     (   4610, 'XIAN80',
                        '', 0, 0
              );
  _cs.Add     (   4022, 'YEMHSL',
                        '', 0, 0
              );
  _cs.Add     (   4310, 'YOFF2000',
                        '', 0, 0
              );
  _cs.Add     (     -1, 'VENUS',
                        'VENUS', 6051920, 0
              );
end;

begin
  prepare_1;
  prepare_2;
end;

//==================================== END ====================================

